# FRONT OFFICE
homepage:
  path: /
  defaults: { _controller: 'Controller\PageController::goHome' }

clients:
  path: /clients
  defaults: { _controller: 'Controller\ClientsController::listClients' }

# BACK OFFICE
admin:
  path: /admin
  defaults: { _controller: 'Controller\PageController::goBack' }
