# FRONT OFFICE
homepage :
  path: /crm-freelance/
  defaults: { _controller: 'Controller\PageController::goHome' }

login :
  path: /crm-freelance/login
  defaults: { _controller: 'Controller\PageController::userLogin' }

clients :
  path: /crm-freelance/clients
  defaults: { _controller: 'Controller\ClientsController::listClients' }

projects-list :
  path: /crm-freelance/projects-list
  defaults: { _controller: 'Controller\ProjectsController::listProjects' }

projects-summary-client :
  path: /crm-freelance/project-cl?id={id}
  defaults: { _controller: 'Controller\ProjectsController::viewProjectClient' }

projects-summary-free :
  path: /crm-freelance/project-fr?id={id}
  defaults: { _controller: 'Controller\ProjectsController::viewProjectFree' }

add-projects-client :
  path: /crm-client/add-projects
  defaults: { _controller: 'Controller\ProjectsController::addProjectClient' }

add-projects-freelance :
  path: /crm-freelance/create-projects
  defaults: { _controller: 'Controller\ProjectsController::addProjectFreelance' }


# BACK OFFICE
super :
  path: /crm-freelance/admin
  defaults: { _controller: 'Controller\PageController::goBack' }

install :
  path : /crm-freelance/install
  defaults: { _controller: 'Controller\InstallController::installDB' }
