# FRONT OFFICE
homepage :
  path: /
  defaults: { _controller: 'Controller\PageController::goHome' }

clients :
  path: /clients
  defaults: { _controller: 'Controller\ClientsController::listClients' }

client :
  path: /client?id={id}
  defaults: { _controller: 'Controller\ClientsController::viewClient' }


# BACK OFFICE
super :
  path: /admin
  defaults: { _controller: 'Controller\PageController::goBack' }
  
install : 
  path : /install
  defaults: { _controller: 'Controller\InstallController::installDB' }